parameters:
  app.output.prefix: "%color.lcyan%<%color.lblue%[%color.cyan%"
  app.output.suffix: ""
  app.output.time_separator: "%color.lblue%]%color.lcyan%> %color.white%"
  app.output.time_format: "H:i:s"
  app.save.base_path: "/app/out"

  color.black: "\e[0;30m"
  color.dgrey: "\e[1;30m"
  color.red: "\e[0;31m"
  color.lred: "\e[1;31m"
  color.green: "\e[0;32m"
  color.lgreen: "\e[1;32m"
  color.brown: "\e[0;33m"
  color.yellow: "\e[1;33m"
  color.blue: "\e[0;34m"
  color.lblue: "\e[1;34m"
  color.magenta: "\e[0;35m"
  color.lmagenta: "\e[1;35m"
  color.cyan: "\e[0;36m"
  color.lcyan: "\e[1;36m"
  color.lgrey: "\e[0;37m"
  color.white: "\e[1;37m"
