services:
  app.utils.savehandler:
    class: App\Utils\SaveHandler
    arguments:
      - "@vendor.filesystem"
      - "%app.save.base_path%"

  app.service.randomimagegenerator:
    class: App\Service\RandomImageGenerator

  app.service.randommonoimagegenerator:
    class: App\Service\RandomMonoImageGenerator

  app.command.generate_random_image:
    class: App\Command\GenerateRandomImageCommand
    arguments:
      - "@app.service.randomimagegenerator"
      - "@app.utils.savehandler"

  app.command.generate_random_mono_image:
    class: App\Command\GenerateRandomMonoImageCommand
    arguments:
      - "@app.service.randommonoimagegenerator"
      - "@app.utils.savehandler"

  vendor.filesystem:
    class: Symfony\Component\Filesystem\Filesystem
